### ISSUE TITLE
Symfony 6.* support

### ISSUE THREAD

**Issue by eddeh** [netgen-layouts/layouts-standard#4]
Hello,

I am not able to install this package on an existing symfony 6.* project due composer conflicts as the package is supported up to version 5.4.13 it seems.
Is there a roadmap/ETA for symfony 6.* support?

**Comment by emodric** [comment]
Hi!

Yes, next version will have Symfony 6 support. Release is planned by the end of the year!

**Comment by eddeh** [comment]
That's great. Thank you for your speedy reply.

**Comment by emodric** [comment]
You're welcome!

Feel free to close this if you don't have any more questions :)

**Comment by eddeh** [comment]
I left it open because I get messages, but I will close it, no problem.

Thanks again.
