### ISSUE TITLE
Migration can only be executed safely on MySQL

### ISSUE THREAD

**Issue by KojoEnch** [netgen-layouts/layouts-standard#6]
Hi, I was searching such a "layout bundle" for a new Symfony project, until I tried to run migrations.

In a nutshell, before I dig into your SQL statements, could you tell us what are the incompatibilities with PostgreSQL ? 
Thanks all for the amazing work !

**Comment by emodric** [comment]
Hi! Some of the migration queries are MySQL specific. We haven't had the chance (or project) to implement pgsql specific ones.

**Comment by ilukac** [comment]
@KojoEnch we have unit test run against pgsql and all pass. There is also a new project which we are developing with pgsql and so far we dind't experence any problem, but it's still not live. The only thing missing are migrations.

**Comment by KojoEnch** [comment]
Hey, thanks all for your quick reply ! @ilukac in order to update the schema, I suppose you rewrote  [the schema dump ](https://github.com/netgen-layouts/layouts-core/blob/master/resources/data/schema.mysql.sql) to pgsql with pgLoader or some other tool then.

**Comment by emodric** [comment]
Schema is already available for tests, but you can use it on your own: https://github.com/netgen-layouts/layouts-core/blob/master/tests/_fixtures/schema/schema.pgsql.sql

**Comment by KojoEnch** [comment]
Amazing.  Yet I have a short question, I'm gonna opening an issue to keep things clean, and leave you in peace then ;) Thanks again for this great package.
