### ISSUE TITLE
Choose layout and fill blocks on the fly

### ISSUE THREAD

**Issue by KojoEnch** [netgen-layouts/layouts-standard#7]
Hi,

As far as I understood the UI and the docs, this tool was thought to create templates and map them with routes, uris...

We can also embed predefined existing content in a layout with Content browser, nice feature. 

But I don't have the full picture. Let take a typical blog context, where the user needs to post some new rich content on a daily basis, with both existing content and new one. Could netgen-layouts be used to **choose a layout and then fill in each block on the fly** when creating / editing a post ?
Thank you !

**Comment by emodric** [comment]
Hi @KojoEnch ! I believe this is best answered by @ilukac , maybe on a Zoom call, so he can better understand your needs?

**Comment by ilukac** [comment]
Yeah, maybe best that I demo the whole thing :)

**Comment by KojoEnch** [comment]
Well, if you have 20 min to dedicate for a demo, that's very kind of you, and might save time to both ! I may follow up through your website then, since this cannot be done here imho.

**Comment by emodric** [comment]
Will close this as @KojoEnch and @ilukac agreed via email on when to hold a demo!
